name: Regenerate Invite & Build

on:
  schedule:
    - cron:  '0 12 */7 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout commit
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ./build/.nvmrc
        cache: npm
        cache-dependency-path: ./build/package-lock.json

    - name: Install Dependencies
      working-directory: ./build
      run: npm ci

    - name: Regenerate Invite & Build Files
      working-directory: ./build
      run: npm start
      env:
        SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }}
        SLACK_USER_COOKIE: ${{ secrets.SLACK_USER_COOKIE }}
    
    - name: Check for Changes
      id: diff
      run: echo "modified=$(if [ -n "$(git diff -- index.html 404.html)" ]; then echo "true"; else echo "false"; fi)" >> $GITHUB_OUTPUT
    
    - name: Get GitHub Actions User
      if: steps.diff.outputs.modified == 'true'
      id: user
      uses: actions/github-script@v7
      with:
        script: |
          const { data } = await github.rest.users.getByUsername({ username: 'github-actions[bot]' });
          core.setOutput('id', data.id);

    - name: Commit & Push Changes
      if: steps.diff.outputs.modified == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "${GITHUB_USER_ID}+github-actions[bot]@users.noreply.github.com"
        git add index.html 404.html
        git commit -m "Updated invite"
        git push origin master
      env:
        GITHUB_USER_ID: ${{ steps.user.outputs.id }}
