name: Regenerate Invite & Build

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 12 */14 * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_USER_TOKEN }

    - name: Navigate to Build
      run: cd build

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}

    - name: Cache Dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ steps.nvm.outputs.NVMRC }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ steps.nvm.outputs.NVMRC }}-
          ${{ runner.os }}-node-

    - name: Install Dependencies
      run: npm ci

    - name: Regenerate Invite & Build Files
      run: npm run build
      env:
        SLACK_USER_TOKEN: ${{ secrets.SLACK_USER_TOKEN }

    - name: Commit & Push Changes
      run: |
        cd ..
        git add index.html
        git add 404.html
        git commit -m "Updated invite"
        git push origin master
